currency_symbols = {
        '$': 'Dollar',
        '¢': 'Cent',
        '₡': 'Colon',
        '₢': 'Cruzeiro',
        '₣': 'Franc',
        '₤': 'Lira',
        '₥': 'Mill',
        '₦': 'Naira',
        '₧': 'Peseta',
        '₨': 'Rupee',
        '₩': 'Won',
        '₪': 'Shekel',
        '₫': 'Dong',
        '₭': 'Kip',
        '₮': 'Tugrik',
        '₯': 'Drachma',
        '₰': 'Penny',
        '₱': 'Peso',
        '₲': 'Guarani',
        '₳': 'Austral',
        '₴': 'Hryvnia',
        '₵': 'Cedi',
        '₸': 'Tenge',
        '₺': 'Lira',
        '₼': 'Manat',
        '₽': 'Ruble',
        '₾': 'Lari',
        '₿': 'Bitcoin',
        '₺': 'Turkish Lira',
        '៛': 'Riel',
        '₹': 'Indian Rupee',
        '₠': 'Euro',
        '₡': 'Costa Rican colon',
        '₢': 'Brazilian Cruzeiro',
        '₣': 'French franc',
        '₤': 'Italian lira',
        '₥': 'mill',
        '₦': 'Nigerian Naira',
        '₧': 'Spanish peseta',
        '₨': 'Pakistan Rupee',
        '₩': 'South Korean won',
        '₪': 'Israeli new shekel',
        '₫': 'Vietnamese dong',
        '₭': 'Lao kip',
        '₮': 'Mongolian tögrög',
        '₯': 'Greek drachma',
        '₰': 'German penny',
        '₱': 'Philippine peso',
        '₲': 'Paraguayan guaraní',
        '₳': 'Argentine austral',
        '₴': 'Ukrainian hryvnia',
        '₵': 'Ghanaian cedi',
        '₸': 'Kazakhstani tenge',
        '₺': 'Turkish lira',
        '₼': 'Azerbaijani manat',
        '₽': 'Russian ruble',
        '₾': 'Georgian lari',
        '₿': 'Bitcoin',
        'Ƀ': 'Bitcoin'
    }



# Define the word lists for numbers, tens, and scales (powers of 1000).
ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten',
        'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen']
tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety']
scales = ['', 'Thousand', 'Million', 'Billion', 'Trillion', 'Quadrillion', 'Quintillion', 'Sextillion',
         'Septillion', 'Octillion', 'Nonillion', 'Decillion', 'Undecillion', 'Duodecillion', 'Tredecillion']
