currency_data = {
    'Lek': [('Leke', 'ALL')],
    '$': [('Dollars', 'USD'), ('Pesos', 'ARS'), ('Dollars', 'AUD'), ('Dollars', 'BSD'), ('Dollars', 'BBD'), ('Dollars', 'BMD'), ('Dollars', 'BND'), ('Dollars', 'CAD'), ('Dollars', 'KYD'), ('Pesos', 'CLP'), ('Pesos', 'COP'), ('Dollars', 'XCD'), ('Colones', 'SVC'), ('Dollars', 'FJD'), ('Dollars', 'GYD'), ('Dollars', 'HKD'), ('Dollars', 'LRD'), ('Pesos', 'MXN'), ('Dollars', 'NAD'), ('Dollars', 'NZD'), ('Dollars', 'SGD'), ('Dollars', 'SBD'), ('Dollars', 'SRD'), ('Dollars', 'TVD'), ('Zimbabwean dollar', 'ZWL')],
    '؋': [('Afghanistan', 'AFN')],
    'ƒ': [('Guilders', 'AWG'), ('Guilders', 'ANG')],
    'ман': [('New Manats', 'AZN')],
    'p.': [('Rubles', 'BYR')],
    '€': [('Euro', 'EUR')],
    'BZ$': [('Dollars', 'BZD')],
    '$b': [('Bolivianos', 'BOB')],
    'KM': [('Convertible Marka', 'BAM')],
    'P': [('Pula', 'BWP')],
    'лв': [('Leva', 'BGN'), ('Tenge', 'KZT'), ('Soms', 'KGS'), ('Sums', 'UZS')],
    'R$': [('Reais', 'BRL')],
    '£': [('Pounds', 'GBP'), ('Pounds', 'EGP'), ('Pounds', 'FKP'), ('Pounds', 'GIP'), ('Pounds', 'GGP'), ('Pounds', 'IMP'), ('Pounds', 'JEP'), ('Pounds', 'LBP'), ('Pounds', 'SHP'), ('Pounds', 'SYP'), ('Liras', 'TRL'), ('South Sudanese pound', 'SSP')],
    '៛': [('Riels', 'KHR')],
    '¥': [('Yuan Renminbi', 'CNY'), ('Yen', 'JPY')],
    '₡': [('Colón', 'CRC')],
    'kn': [('Kuna', 'HRK')],
    '₱': [('Pesos', 'CUP')],
    'Kč': [('Koruny', 'CZK')],
    'kr': [('Kroner', 'DKK'), ('Kronur', 'ISK'), ('Krone', 'NOK'), ('Kronor', 'SEK')],
    '¢': [('Cedis', 'GHC')],
    'Q': [('Quetzales', 'GTQ')],
    'L': [('Lempiras', 'HNL'), ('Moldovan leu', 'MDL'), ('Swazi lilangeni', 'SZL')],
    'Ft': [('Forint', 'HUF')],
    '₹': [('Rupees', 'INR')],
    'Rp': [('Rupiahs', 'IDR')],
    '﷼': [('Rials', 'IRR'), ('Rials', 'OMR'), ('Rials', 'QAR'), ('Riyals', 'SAR'), ('Rials', 'YER')],
    '₪': [('New Shekels', 'ILS')],
    'J$': [('Dollars', 'JMD')],
    '₩': [('Won', 'KPW'), ('Won', 'KRW')],
    '₭': [('Kips', 'LAK')],
    'Ls': [('Lati', 'LVL')],
    'CHF': [('Switzerland Francs', 'CHF')],
    'Lt': [('Litai', 'LTL')],
    'ден': [('Denars', 'MKD')],
    'RM': [('Ringgits', 'MYR')],
    '₨': [('Rupees', 'MUR'), ('Rupees', 'NPR'), ('Rupees', 'PKR'), ('Rupees', 'SCR'), ('Rupees', 'LKR')],
    '₮': [('Tugriks', 'MNT')],
    'MT': [('Meticais', 'MZN')],
    'C$': [('Cordobas', 'NIO')],
    '₦': [('Nairas', 'NGN')],
    'B/.': [('Balboa', 'PAB')],
    'Gs': [('Guarani', 'PYG')],
    'S/.': [('Nuevos Soles', 'PEN')],
    'Php': [('Pesos', 'PHP')],
    'zł': [('Zlotych', 'PLN')],
    'lei': [('New Lei', 'RON')],
    'руб': [('Rubles', 'RUB')],
    'Дин.': [('Dinars', 'RSD')],
    'S': [('Shillings', 'SOS')],
    'R': [('Rand', 'ZAR')],
    'NT$': [('New Dollars', 'TWD')],
    '฿': [('Baht', 'THB')],
    'TT$': [('Dollars', 'TTD')],
    '₺': [('Lira', 'TRY')],
    '₴': [('Hryvnia', 'UAH')],
    '$U': [('Pesos', 'UYU')],
    'Bs': [('Bolivares Fuertes', 'VEF')],
    '₫': [('Dong', 'VND')],
    'Z$': [('Zimbabwe Dollars', 'ZWD')],
    'DA': [('Algerian dinar', 'DZD')],
    'Kz': [('Angolan kwanza', 'AOA')],
    '֏': [('Armenian dram', 'AMD')],
    'BD': [('Bahraini dinar', 'BHD')],
    '৳': [('Bangladeshi taka', 'BDT')],
    'CFA': [('West African CFA franc', 'XOF')],
    'FBu': [('Burundian franc', 'BIF')],
    'FCFA': [('Central African CFA franc', 'XAF')],
    'Esc': [('Cape Verdean escudo', 'CVE')],
    'CF': [('Comorian franc', 'KMF')],
    'Fdj': [('Djiboutian franc', 'DJF')],
    'RD$': [('Dominican peso', 'DOP')],
    'Nkf': [('Eritrean nakfa', 'ERN')],
    'Br': [('Ethiopian birr', 'ETB')],
    '₣': [('CFP franc', 'XPF')],
    'D': [('Gambian dalasi', 'GMD')],
    'ლ': [('Georgian lari', 'GEL')],
    'GH₵': [('Ghanaian cedi', 'GHS')],
    'FG': [('Guinean franc', 'GNF')],
    'ع.د': [('Iraqi dinar', 'IQD')],
    'د.ا': [('Jordanian dinar', 'JOD')],
    'Ksh': [('Kenyan shilling', 'KES')],
    'د.ك': [('Kuwaiti dinar', 'KWD')],
    'ل.د': [('Libyan dinar', 'LYD')],
    'MOP$': [('Macanese pataca', 'MOP')],
    'Ar': [('Malagasy ariary', 'MGA')],
    'MK': [('Malawian kwacha', 'MWK')],
    'Rf': [('Maldivian rufiyaa', 'MVR')],
    'UM': [('Mauritanian ouguiya', 'MRO')],
    'MAD': [('Moroccan dirham', 'MAD')],
    'K': [('Myanmar kyat', 'MMK'), ('Papua New Guinean kina', 'PGK')],
    'R₣': [('Rwandan franc', 'RWF')],
    'WS$': [('Samoan tālā', 'WST')],
    'Db': [('São Tomé and Príncipe dobra', 'STD')],
    'Le': [('Sierra Leonean leone', 'SLL')],
    'ج.س': [('Sudanese pound', 'SDG')],
    'ЅM': [('Tajikistani somoni', 'TJS')],
    'TSh': [('Tanzanian shilling', 'TZS')],
    'T$': [('Tongan paʻanga', 'TOP')],
    'DT': [('Tunisian dinar', 'TND')],
    'T': [('Turkmenistani manat', 'TMT')],
    'USh': [('Ugandan shilling', 'UGX')],
    'د.إ': [('United Arab Emirates dirham', 'AED')],
    'VT': [('Vanuatu vatu', 'VUV')],
    'ZK': [('Zambian kwacha', 'ZMW')],
}


# Define the word lists for numbers, tens, and THOUSANDS
ONES = [
    "",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
]

TENS = [
    "",
    "",
    "twenty",
    "thirty",
    "forty",
    "fifty",
    "sixty",
    "seventy",
    "eighty",
    "ninety",
]

THOUSANDS = [
    "",
    "thousand",
    "million",
    "billion",
    "trillion",
    "quadrillion",
    "quintillion",
    "sextillion",
    "septillion",
    "octillion",
    "nonillion",
    "decillion",
    "undecillion",
    "duodecillion",
    "tredecillion",
    "quattuordecillion",
    "quindecillion",
    "sexdecillion",
    "septendecillion",
    "octodecillion",
    "novemdecillion",
    "vigintillion",
]
